JCC = javac

default: TeachingRecord.class
	jar cfmv TeachingRecord.jar ejs320/Manifest.txt TeachingRecord.class 

TeachingRecord.class: TeachingRecord.java
	$(JCC) TeachingRecord.java

#clean:
#	$(RM) *.class
